name: bedrock
recipe: wordpress

proxy:
  theme:
    - localhost:3000

config:
  php: '7.4'
  via: nginx
  webroot: web
  database: mariadb:10.4
  xdebug: true

services:
  theme:
    type: node
    services:
      ports:
        - 3000:3000

tooling:
  yarn:
    service: theme