# project information
name: bedrock
recipe: wordpress

# performance tweaks
excludes:
  - vendor
  - node_modules

# events
events:
  pre-stop:
    - appserver: echo "Backing up database..."
    - appserver: wp db export --path=/app/web
    - appserver: echo "Database successfully backed up"

# proxy urls
proxy:
  mailhog:
    - mail.bedrock.lndo.site

# configuration
config:
  php: '7.4'
  via: nginx
  webroot: web
  database: mariadb:10.4
  xdebug: true

# services
services:

  # theming for wordpress
  theme:
    type: node

  # mailhog for intercepting mail in dev
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver

  # redis for object caching
  redis:
    type: redis:6
    persist: true
    portforward: false
    config: 
      server: config/redis.conf

# tooling
tooling:
  npm:
    service: theme
  npx:
    service: theme
  node:
    service: theme
  gulp:
    service: theme
  yarn:
    service: theme
  redis-cli:
    service: redis
  php:
    service: appserver
  sync:local:
    service: appserver
    description: Sync production server to local
    cmd: 
      - echo '\n--syncing file uploads...'
      - rsync -av edutcmi:/var/www/tcmi.edu/wordpress/wp-content/uploads /app/wordpress/wp-content
      - echo '\n--export production database'
      - ssh edutcmi 'cd /var/www/tcmi.edu/wordpress && wp db export production.sql'
      - echo '\n--importing production database...'
      - rsync -av edutcmi:/var/www/tcmi.edu/wordpress/production.sql /app/wordpress/
      - cd /app/wordpress && wp db import production.sql
      - cd /app/wordpress && wp cache flush
      - echo '\n--deactivating production plugins...'
      - cd /app/wordpress && wp plugin deactivate wp-super-cache fast-velocity-minify all-in-one-wp-security-and-firewall
      - echo '\n--activating development plugins...'
      - cd /app/wordpress && wp plugin activate query-monitor
      - echo '\n--updating production url to lando url...'
      - cd /app/wordpress && wp search-replace 'www3.tcmi.edu' 'tcmi.lndo.site'
      - cd /app/wordpress && wp cache flush
  deploy:production:
    service: appserver
    description: Deploy code to production
    cmd:
      - echo '\n--deploying code to production'
      - ssh edutcmi 'cd /var/www/tcmi.edu && git pull'