# development environment
development:
  enable:
    - query-monitor/query-monitor.php

# all environments
global:
  enable:
    - wp-user-profiles/wp-user-profiles.php
    - wp-user-avatars/wp-user-avatars.php
